# Generated by Django 2.0.1 on 2018-01-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('PR', 'Programming'), ('NT', 'Networking'), ('PC', 'PC Technichian')], default='PC', max_length=2, verbose_name='Coursework'),
        ),
    ]
